import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
} from 'typeorm';

/**
 * Entidad que mapea la tabla sena.tema de PostgreSQL.
 *
 * DDL original:
 *   CREATE TABLE sena.tema (
 *     id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     nombre_tema varchar NOT NULL
 *   );
 */
@Entity({ name: 'tema', schema: 'sena' })
export class Tema {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: number;

  @Column({ name: 'nombre_tema', type: 'varchar', nullable: false })
  nombreTema: string;

  @Column({ name: 'tips', type: 'jsonb', nullable: true })
  tips: object;
}
